hepsi: derle calistir

derle:
	gcc -I ./include/ -o ./lib/Node.o -c ./src/Node.c
	gcc -I ./include/ -o ./lib/LinkedList.o -c ./src/LinkedList.c
	gcc -I ./include/ -o ./bin/Test ./lib/Node.o ./lib/LinkedList.o ./src/Test.c

calistir:
	./bin/Test